spring:
  config:
    import:
      - classpath:config/secret-local.yaml
  datasource:
  url: jdbc:h2:tcp://localhost/~/jbTraining
  username: sa
  password: 123
  driver-class-name: org.h2.Driver

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true

logging.level:
  org.hibernate.SQL: debug